apiVersion: v1
kind: Service
metadata:
  name: todo-api-svc
spec:
  type: ClusterIP
  selector:
    app: todo-api
    tier: backend
  ports:
    - port: 3001 #svc port
      targetPort: 3001 #container port
